#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz && sync

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# Check if wld is running
	if ! pidof wld >/dev/null 2>&1; then
		logger -t pwhm_boot "wld is not running, restarting prplmesh_whm"
		/etc/init.d/prplmesh_whm restart
	fi
	# set leds to normal state
	. /etc/diag.sh
	set_state done

	# Apply SMP affinity once after the first PHY is registered.
	while ! iw dev | grep -q "Interface"; do
		echo "Waiting for driver initialization" > /dev/null
		sleep 2
	done
	. /lib/smp_affinity_settings.sh
	enable_smp_affinity_wifi
}
