#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz && sync

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done

	# enable_smp_affinity
	enable_smp_affinity=$(uci -q get wireless.mac80211.enable_smp_affinity)
	if [ "$enable_smp_affinity" -eq 1 ] && [ -f "/lib/smp_affinity_settings.sh" ]; then
		. /lib/smp_affinity_settings.sh
		enable_smp_affinity_wifi
	fi
}
