#!/bin/sh /etc/rc.common
# Copyright (C) 2026 SoftAtHome

START=15
USE_PROCD=1

CFG_MOUNT="/cfg"
SECURESTORE_LABEL="securestore"

start_service() {

    mkdir -p ${CFG_MOUNT}

    SECURESTORE_DEV=$(blkid -L ${SECURESTORE_LABEL})

    if [ -z "${SECURESTORE_DEV}" ]; then
        echo "ERROR: securestore partition not found"
        return 1
    fi

    mount -o rw,noatime,nodev,nosuid ${SECURESTORE_DEV} ${CFG_MOUNT}

    if [ $? -ne 0 ]; then
        echo "ERROR: failed to mount securestore"
        return 1
    fi

    echo "securestore mounted on ${CFG_MOUNT}"
}
